### PR TITLE
fix/cgi/output

### LINKED ISSUE #81: cgi output
The cgi should not produce the status line (if it wants to set the status code it has to set a specific header).
Also it is using only LF instead of CRLF.

so we have to change the message parser a bit to support this.

### PR DESCRIPTION
**Pull request by Jakobus42**
This PR includes:
 - CGI output parsing according to RFC (i.e no CR, response end on hangup and no status line)
 - extracting status code and reason from status header
The cgi now works with the python cgi library and random scripts from the web as it is now CGI/1.1 compliant.

note:
I know it is implemented in a super weird way but idc about how it looks anymore I just want to finish this project .-.

Closes #81

### CODE REVIEW

File: src/core/CGIEventHandler.cpp [hunk 1]
```diff
@@ -15,6 +15,12 @@ namespace core {
 		, m_response(response)
 		, m_bytesWritten(0)
 		, m_responseParser() {
+		http::ResponseParserConfig conf;
+		// weird stuff
+		conf.messageParserConfig.requireCR = false;
+		conf.messageParserConfig.requireStartLine = false;
+		conf.messageParserConfig.parseBodyWithoutContentLength = true; // I hate this
+		m_responseParser.setConfig(conf);
```
Comment (rwxg) [inline src/core/CGIEventHandler.cpp:23]: Weird indeed. Why not create the config object outside of the handler and pass it as a param?

File: src/core/CGIProcessor.cpp [hunk 2]
```diff
@@ -86,7 +89,9 @@ namespace core {
 		m_ioState |= IO_WRITE_COMPLETE;
 	}
 
-	void CGIProcessor::notifyIOError() {
+	void CGIProcessor::notifyIOError(http::StatusCode statusCode, const std::string& reason) {
+		m_lastIOStatusCode = statusCode;
+		m_lastIOErrorReason = reason;
```
Comment (rwxg) [inline src/core/CGIProcessor.cpp:94]: yeah, this makes sense

File: src/core/CGIProcessor.cpp [hunk 3]
```diff
@@ -98,7 +103,10 @@ namespace core {
 		if (shared::file::isReadable(scriptPath) == false) {
 			throw http::HttpException(http::FORBIDDEN, "script is not readable: " + std::string(std::strerror(errno)));
 		}
-		const std::string& interpreter = getInterpreter(scriptPath);
+
+		m_scriptName = scriptPath.substr(8 /* /cgi-bin/ */);
```
Comment (rwxg) [inline src/core/CGIProcessor.cpp:107]: 👍

**Review by rwxg — CHANGES_REQUESTED** [review]
Couple of things, nothing major though. Looks good otherwise.

File: src/core/CGIEventHandler.cpp (hunk 1 above)
Comment (Jakobus42) [reply src/core/CGIEventHandler.cpp:23]: I dont want to set all of the configs so I have to do it this way.

**Review by rwxg — APPROVED** [review]
<3
