### PR TITLE
fix: validate host header

### LINKED ISSUE #83: Request parser doesn't parse mandatory headers
A feature from the pre-refactor RequestParser is missing. The Host header is mandatory and we rely on it to generate links for the file index.

Image

### PR DESCRIPTION
**Pull request by Jakobus42**
host header validation in request parsing.
(and http version validation :p but shhhh)

Closes #83

### CODE REVIEW

File: src/http/RequestParser.cpp [hunk 1]
```diff
@@ -135,5 +139,31 @@ namespace http {
 		// also, should we check if we accept the script here?
 	}
 
+	void RequestParser::interpretHeaders() {
+		this->AMessageParser::interpretHeaders();
```
Comment (rwxg) [inline src/http/RequestParser.cpp:143]: Exactly what I had in mind ❤️

File: src/http/RequestParser.cpp [hunk 2]
```diff
@@ -63,7 +63,11 @@ namespace http {
 			parseUriAbsoluteForm(uriView);
 		}
 
-		m_request->setVersion(line.substr(secondSpace + 1));
+		shared::string::StringView versionView = line.substr(secondSpace + 1);
+		if (versionView != shared::string::StringView("HTTP/1.1")) {
+			throw HttpException(HTTP_VERSION_NOT_SUPPORTED, "invalid http version");
+		}
+		m_request->setVersion(versionView);
```
Comment (rwxg) [inline src/http/RequestParser.cpp:70]: 👍💦

**Review by rwxg — APPROVED** [review]
Looks just like what I had in mind, as long as this actually gets called when we call interpretHeaders() (which I think is only called in parseStartLine, which is why I'm not certain that it does), then that's perfect.
