### PR TITLE
fix: better connection timeout handling

### LINKED ISSUE #77: segfault in dispatcher
Currently if we have a timouted connection and we press control c we get a double free in the dispatcher.

### PR DESCRIPTION
**Pull request by Jakobus42**
I am not sure if this is 100% fine and if it would fuck up in some cases but we will see during testing

Closes #77

### CODE REVIEW

File: src/core/ConnectionEventHandler.cpp [hunk 1]
```diff
@@ -42,6 +42,11 @@ namespace core {
 		LOG_CONTEXT("read event  | server: " + m_vServer.getVirtualServerInfo() +
 					" | connection: " + m_connection.getConnectionInfo());
 
+		if (m_connection.hasTimedOut()) {
+			LOG_INFO("connection timed out");
+			return io::UNREGISTER;
+		}
+
```
Comment (rwxg) [inline src/core/ConnectionEventHandler.cpp:49]: I guess we can just drop the connection after timeout even if the client then wants to send us something.

Might be more consistent that way, otherwise I would have given the client some leniency, as onReadable should only happen when the client is actually showing activity.

**Review by rwxg — APPROVED** [review]
Looks alright. Let's just drop clients after timeout regardless of whether they end up wanting to send right in that moment, that way we have more consistent behaviour.
