### PR TITLE
Fix/cgi/fds

### LINKED ISSUE #70: cgi open fds
currently we get valgrind errors after executing the cgi.
make sure to close all fds before execve.

### PR DESCRIPTION
**Pull request by Jakobus42**
If everything works fine in the child we close all the open fds. (we just have to make sure that no request handler has anything open while we do the cgi processing)

if the child process fails for some reason I will make sure to properly unregister and free all the handlers registered with epoll.
will be done in issue #69

I am not too happy with this solutions because it scares me.

Closes #70

### CODE REVIEW

File: include/io/AMultiplexer.hpp [hunk 1]
```diff
@@ -46,9 +48,18 @@ namespace io {
...
+					::close(m_fd);
+					m_fd = -1;
+				}
+			}
+
 		protected:
 			typedef std::map<int32_t, uint32_t> EventMap;
 
+			int32_t m_fd;
+
```
Comment (rwxg) [inline include/io/AMultiplexer.hpp:62]: Makes sense to just put this here instead of the derived classes. 👍

File: src/core/CGIProcessor.cpp [hunk 2]
```diff
@@ -100,13 +100,16 @@ namespace core {
 
 		if (m_pid == 0) {
 			try {
-				prepareEnviorment(request);
-
-				m_inputPipe.closeWriteEnd();
-				m_outputPipe.closeReadEnd();
+				m_dispatcher.close(); // super sus
```
Comment (rwxg) [inline src/core/CGIProcessor.cpp:103]: 📮

**Review by rwxg — APPROVED** [review]
Sometimes you gotta face the danger head on & do things that frighten you. Only time & testing will tell in this case, I guess. LGTM.
