### PR TITLE
fix/cgi/exit

### LINKED ISSUE #69: child process failure
make sure to unwind the stack when child exits.
This isnt a real issue but maybe for some evaluators.

### PR DESCRIPTION
**Pull request by Jakobus42**
- unwinding the stack on child process failure
- suppressing multiplexer errors from child as we close all of the registered fds including the multiplexer fd which coused a lot of noice in the logs.
- also monitoring for hangup now so we get notified when the child DIES

Closes #69

### CODE REVIEW

File: src/core/CGIProcessor.cpp [hunk 1]
```diff
@@ -121,20 +120,23 @@ namespace core {
 				execve(interpreter.c_str(), argv, m_env);
 				throw std::runtime_error("execve() failed: " + std::string(std::strerror(errno)));
 			} catch (const std::exception& e) {
+				m_pid = -1; // dont kill process on destruction
+				close(STDIN_FILENO);
+				close(STDOUT_FILENO);
 				LOG_ERROR("child process: " + std::string(e.what()));
-				std::exit(EXIT_FAILURE);
+				throw "unwind this shiiiiittt"; // this will be catched in the main .-.
```
Comment (rwxg) [inline src/core/CGIProcessor.cpp:127]: *caught

:^)

File: src/core/CGIProcessor.cpp [hunk 2]
```diff
@@ -121,20 +120,23 @@ namespace core {
 				execve(interpreter.c_str(), argv, m_env);
 				throw std::runtime_error("execve() failed: " + std::string(std::strerror(errno)));
 			} catch (const std::exception& e) {
+				m_pid = -1; // dont kill process on destruction
```
Comment (rwxg) [inline src/core/CGIProcessor.cpp:123]: Yeah, that works.

**Review by rwxg — APPROVED** [review]
Don't see anything wrong here. Nice going!
